# Generated by Django 3.2.16 on 2022-11-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20221121_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updaded',
            new_name='updated',
        ),
    ]
