# Generated by Django 3.2.16 on 2022-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postguest',
            name='content',
            field=models.TextField(max_length=750),
        ),
    ]
