# Generated by Django 3.2.16 on 2022-11-22 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_alter_postguest_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postguest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postguest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
