# Generated by Django 3.2.16 on 2022-11-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_postguest_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postguest',
            name='slug',
        ),
    ]
