# Generated by Django 3.2.16 on 2022-11-25 14:58

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('phone_nr', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_nr', models.AutoField(primary_key=True, serialize=False)),
                ('cabin', models.CharField(choices=[('SAL', 'Cabin Sälen'), ('OLA', 'Öland')], max_length=6)),
                ('guests', models.IntegerField(choices=[(1, '1 Guest'), (2, '2 Guests'), (3, '3 Guests'), (4, '4 Guests'), (5, '5 Guests'), (6, '6 Guests'), (7, '2 Guests'), (8, '2 Guests'), (9, '9 Guests'), (10, '2 Guests'), (11, '2 Guests'), (12, '12 Guests')], default=2)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='cabins_reservations.guest')),
            ],
        ),
    ]
