# Generated by Django 3.2.16 on 2022-11-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins_reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='arrival',
            new_name='arrival_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_nr',
            new_name='booking_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='departure',
            new_name='departure_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('canceled', 'canceled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cabin',
            field=models.CharField(choices=[('SAL', 'Sälen'), ('OLA', 'Öland')], max_length=6),
        ),
    ]
