# Generated by Django 3.2.16 on 2022-11-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins_reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('cabin_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
