# Generated by Django 3.2.16 on 2022-11-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabins_reservations', '0002_cabin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cabin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabins_reservations.cabin'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(choices=[(1, '1 Guest'), (2, '2 Guests'), (3, '3 Guests'), (4, '4 Guests'), (5, '5 Guests'), (6, '6 Guests'), (7, '2 Guests'), (8, '2 Guests'), (9, '9 Guests'), (10, '2 Guests'), (11, '2 Guests'), (12, '12 Guests'), (13, '14 Guests'), (14, '14 Guests')], default=2),
        ),
    ]
