# Generated by Django 3.2.16 on 2022-11-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins_reservations', '0004_alter_booking_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateTimeField(),
        ),
    ]
