# Generated by Django 3.2.16 on 2022-11-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins_reservations', '0005_auto_20221128_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
